# 只启动 fastapi 服务, mysq, redis, nginx 服务使用云端
services:
  fastapi:
    container_name: "${CONTAINER_NAME_PREFIX}-${FASTAPI_CONTAINER_NAME}"
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile

    env_file:
      - .env

    # 如果 mysql, redis 等跑在宿主机上，取消下面注释，切换为 hosts 模式后 ports 配置将不会生效
    # network_mode: "host"

    ports:
      - "${RUNTIME_PORT}:${RUNTIME_PORT}"

    volumes:
      - ./public:/app/public

    command: python start.py
