# 只启动 server 服务, mysq, redis 等服务使用云端
# 负载均衡和集群部署时可使用此配置
services:
  server:
    build:
      context: ./
      dockerfile: Dockerfile

    env_file:
      - .env

    ports:
      - "${RUNTIME_PORT}:${RUNTIME_PORT}"

    volumes:
      - ./public:/app/public

    command: python start.py
