# Celery 容器
# 可单独启动，执行后台任务，集群部署时此容器只启动一个实例即可，且 mysql & redis 需要部署在云端
services:
  celery:
    container_name: "${CONTAINER_NAME_PREFIX}-${CELERY_CONTAINER_NAME}"
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile.celery
    env_file:
      - .env
    command: /entrypoint.sh
    networks:
      - fastbooster_network

networks:
  fastbooster_network:
