# 开发环境下只启动 mysql 和 redis 容器，fastapi 在宿主机上运行，方便调试
services:
  mysql:
    container_name: "${CONTAINER_NAME_PREFIX}-${DB_CONTAINER_NAME}"
    restart: always
    image: mysql:8.0.35
    ports:
      - ${DB_EXPOSE_PORT}:3306
    volumes:
      - ./volumes/mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PWD}
      MYSQL_ROOT_PASSWORD: ${DB_PWD}
      MYSQL_INITDB_SKIP_TZINFO: just_do_it
      TZ: Asia/Shanghai
    command:
      --character-set-server=${DB_CHARSET}
      --collation-server=${DB_COLLATION}
      --explicit_defaults_for_timestamp=true
      --lower_case_table_names=1
      --max_allowed_packet=128M
    networks:
      - fastbooster_network

  redis:
    container_name: "${CONTAINER_NAME_PREFIX}-${REDIS_CONTAINER_NAME}"
    restart: always
    image: redis:7.2.1
    volumes:
      - ./docker/redis/redis.conf:/etc/redis/redis.conf:ro
      - ./volumes/redis/:/data
    command: /bin/sh -c "echo 'vm.overcommit_memory = 1' >> /etc/sysctl && redis-server /etc/redis/redis.conf --appendonly yes --requirepass ${REDIS_PWD}"
    ports:
      - ${REDIS_EXPOSE_PORT}:6379
    networks:
      - fastbooster_network

networks:
  fastbooster_network:
