# 只启动 server 服务, mysq, redis 等服务使用云端
services:
  server:
    build:
      context: ./
      dockerfile: Dockerfile

    env_file:
      - .env

    ports:
      - "${RUNTIME_PORT}:${RUNTIME_PORT}"

    command: /entrypoint.sh
