"""Init

Revision ID: 08f58d3866d1
Revises: 
Create Date: 2024-05-16 19:25:00.044406

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08f58d3866d1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('loginlog',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='ID'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='用户ID'),
    sa.Column('nickname', sa.String(length=50), nullable=True, comment='昵称'),
    sa.Column('ipaddr', sa.String(length=50), nullable=True, comment='IP地址'),
    sa.Column('user_agent', sa.String(length=500), nullable=True, comment='浏览器信息'),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True, comment='创建时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='登录日志'
    )
    op.create_table('permission',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='ID'),
    sa.Column('pid', sa.Integer(), server_default='0', nullable=True, comment='上级ID'),
    sa.Column('name', sa.String(length=50), nullable=False, comment='名称'),
    sa.Column('icon', sa.String(length=50), nullable=True, comment='图标'),
    sa.Column('component_name', sa.String(length=50), nullable=True, comment='路由组件名称'),
    sa.Column('asc_sort_order', sa.Integer(), server_default='0', nullable=True, comment='排序'),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='权限表'
    )
    op.create_table('role',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='ID'),
    sa.Column('name', sa.String(length=50), nullable=False, comment='角色名称'),
    sa.Column('permissions', sa.Text(), nullable=True, comment='权限列表'),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='角色表'
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='ID'),
    sa.Column('pid', sa.Integer(), server_default='0', nullable=True, comment='所属上级'),
    sa.Column('agent_id', sa.Integer(), server_default='0', nullable=True, comment='所属代理'),
    sa.Column('phone_code', sa.String(length=10), server_default='86', nullable=True, comment='手机代码'),
    sa.Column('phone', sa.String(length=50), nullable=True, comment='手机'),
    sa.Column('email', sa.String(length=50), nullable=True, comment='邮箱'),
    sa.Column('nickname', sa.String(length=50), nullable=True, comment='昵称'),
    sa.Column('gender', sa.String(length=50), nullable=True, comment='性别'),
    sa.Column('avatar', sa.String(length=255), nullable=True, comment='头像'),
    sa.Column('promotion_code', sa.String(length=50), nullable=True, comment='推广码'),
    sa.Column('password_salt', sa.String(length=255), nullable=True, comment='密码盐'),
    sa.Column('password_hash', sa.String(length=255), nullable=True, comment='密码哈希'),
    sa.Column('role_id', sa.Integer(), server_default='0', nullable=True, comment='角色ID'),
    sa.Column('is_admin', sa.SmallInteger(), server_default='0', nullable=True, comment='是否管理员'),
    sa.Column('is_robot', sa.SmallInteger(), server_default='0', nullable=True, comment='是否机器人'),
    sa.Column('auto_memo', sa.String(length=255), nullable=True, comment='自动备注'),
    sa.Column('back_memo', sa.String(length=255), nullable=True, comment='后台备注'),
    sa.Column('wechat_openid', sa.String(length=50), nullable=True, comment='OpenID'),
    sa.Column('wechat_unionid', sa.String(length=50), nullable=True, comment='UnionID'),
    sa.Column('wechat_refresh_token', sa.String(length=255), nullable=True, comment='微信RefreshToken'),
    sa.Column('wechat_access_token', sa.String(length=255), nullable=True, comment='微信AccessToken'),
    sa.Column('wechat_access_token_expired_at', sa.Integer(), nullable=True, comment='微信AccessToken过期时间'),
    sa.Column('join_ip', sa.Integer(), nullable=True, comment='注册IP'),
    sa.Column('join_at', sa.TIMESTAMP(), nullable=True, comment='注册时间'),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='用户表'
    )
    op.create_index('idx_email', 'user', ['email'], unique=False)
    op.create_index('idx_phone', 'user', ['phone'], unique=False)
    op.create_index('idx_pid', 'user', ['pid'], unique=False)
    op.create_index('idx_role', 'user', ['role_id'], unique=False)
    op.create_index('idx_wechat_openid', 'user', ['wechat_openid'], unique=False)
    op.create_index('idx_wechat_unionid', 'user', ['wechat_unionid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_wechat_unionid', table_name='user')
    op.drop_index('idx_wechat_openid', table_name='user')
    op.drop_index('idx_role', table_name='user')
    op.drop_index('idx_pid', table_name='user')
    op.drop_index('idx_phone', table_name='user')
    op.drop_index('idx_email', table_name='user')
    op.drop_table('user')
    op.drop_table('role')
    op.drop_table('permission')
    op.drop_table('loginlog')
    # ### end Alembic commands ###
