"""Init

Revision ID: dac0ba41d317
Revises: 
Create Date: 2024-08-19 23:21:26.510293

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'dac0ba41d317'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cms_adspace',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='ID'),
    sa.Column('name', sa.String(length=50), nullable=False, comment='广告名称'),
    sa.Column('width', sa.Integer(), server_default='0', nullable=True, comment='推荐宽度'),
    sa.Column('height', sa.Integer(), server_default='0', nullable=True, comment='推荐高度'),
    sa.Column('status', sa.String(length=10), server_default='enabled', nullable=False, comment='状态: enabled/disabled'),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='广告位',
    mariadb_engine='InnoDB',
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_cms_adspace_name'), 'cms_adspace', ['name'], unique=False)
    op.create_table('cms_banner',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='ID'),
    sa.Column('adspace_id', sa.Integer(), nullable=False, comment='广告位ID'),
    sa.Column('position', sa.String(length=255), server_default='center', nullable=False, comment='位置:left|right|center|top|bottom'),
    sa.Column('title', sa.String(length=255), nullable=False, comment='标题'),
    sa.Column('subtitle', sa.String(length=255), nullable=True, comment='子标题'),
    sa.Column('description', sa.String(length=255), nullable=True, comment='描述'),
    sa.Column('content', sa.String(length=500), nullable=True, comment='详细内容'),
    sa.Column('pc_cover', sa.String(length=255), nullable=True, comment='PC端封面图'),
    sa.Column('mobile_cover', sa.String(length=255), nullable=True, comment='移动端封面图'),
    sa.Column('button_title', sa.String(length=255), nullable=True, comment='按钮标题'),
    sa.Column('button_url', sa.String(length=255), nullable=True, comment='按钮地址'),
    sa.Column('status', sa.String(length=10), server_default='enabled', nullable=False, comment='状态: enabled/disabled'),
    sa.Column('asc_sort_order', sa.Integer(), server_default='0', nullable=True, comment='排序'),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='广告资源',
    mariadb_engine='InnoDB',
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_cms_banner_adspace_id'), 'cms_banner', ['adspace_id'], unique=False)
    op.create_table('cms_city',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='ID'),
    sa.Column('pid', sa.Integer(), server_default='0', nullable=False, comment='上级ID'),
    sa.Column('name', sa.String(length=50), nullable=False, comment='地区名称'),
    sa.Column('level', sa.SmallInteger(), server_default='0', nullable=False, comment='等级:0省或直辖市,1市,2县'),
    sa.Column('pinyin', sa.String(length=255), nullable=True, comment='拼音'),
    sa.Column('prefix', sa.String(length=1), nullable=True, comment='拼音首字母缩写'),
    sa.Column('weight', sa.Integer(), server_default='0', nullable=True, comment='排序权重'),
    sa.Column('is_hot', sa.SmallInteger(), server_default='0', nullable=True, comment='是否为热门:0否,1是'),
    sa.PrimaryKeyConstraint('id'),
    comment='城市表',
    mariadb_engine='InnoDB',
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_cms_city_name'), 'cms_city', ['name'], unique=False)
    op.create_index(op.f('ix_cms_city_pid'), 'cms_city', ['pid'], unique=False)
    op.create_index(op.f('ix_cms_city_pinyin'), 'cms_city', ['pinyin'], unique=False)
    op.create_table('cms_media',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='ID'),
    sa.Column('file_name', sa.String(length=255), nullable=True, comment='文件名称'),
    sa.Column('file_type', sa.String(length=32), nullable=True, comment='文件类型'),
    sa.Column('file_size', sa.Integer(), nullable=True, comment='文件大小'),
    sa.Column('file_path', sa.String(length=255), nullable=True, comment='文件路径'),
    sa.Column('oss_url', sa.String(length=255), nullable=True, comment='OSS地址'),
    sa.Column('op_user_id', sa.Integer(), nullable=False, comment='操作员ID'),
    sa.Column('op_user_name', sa.String(length=100), nullable=False, comment='操作员名称'),
    sa.Column('related_type', sa.String(length=32), nullable=True, comment='关联类别'),
    sa.Column('related_id', sa.Integer(), server_default='0', nullable=True, comment='关联ID'),
    sa.Column('view_num', sa.Integer(), server_default='0', nullable=True, comment='浏览量/下载量'),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True, comment='创建时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='媒体文件',
    mariadb_engine='InnoDB',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_cms_media_file_type'), 'cms_media', ['file_type'], unique=False)
    op.create_index(op.f('ix_cms_media_op_user_id'), 'cms_media', ['op_user_id'], unique=False)
    op.create_index(op.f('ix_cms_media_related_id'), 'cms_media', ['related_id'], unique=False)
    op.create_table('cms_post',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='ID'),
    sa.Column('pid', sa.Integer(), server_default='0', nullable=True, comment='上级ID'),
    sa.Column('category_id', sa.Integer(), server_default='0', nullable=True, comment='分类ID'),
    sa.Column('user_id', sa.Integer(), server_default='0', nullable=True, comment='用户ID'),
    sa.Column('title', sa.String(length=255), nullable=False, comment='标题'),
    sa.Column('subtitle', sa.String(length=255), nullable=False, comment='副标题'),
    sa.Column('keywords', sa.String(length=50), nullable=True, comment='关键字'),
    sa.Column('digest', sa.String(length=50), nullable=True, comment='摘要'),
    sa.Column('content', mysql.MEDIUMTEXT(), nullable=False, comment='内容'),
    sa.Column('author', sa.String(length=50), nullable=True, comment='作者'),
    sa.Column('editor', sa.String(length=50), nullable=True, comment='责编'),
    sa.Column('source', sa.String(length=50), nullable=True, comment='来源'),
    sa.Column('source_url', sa.String(length=1000), nullable=True, comment='来源URL'),
    sa.Column('hero_image_url', sa.String(length=1000), nullable=True, comment='首图'),
    sa.Column('price', sa.DECIMAL(precision=10, scale=4), server_default='0', nullable=True, comment='价格'),
    sa.Column('price_point', sa.Integer(), server_default='0', nullable=True, comment='积分价格'),
    sa.Column('view_num', sa.Integer(), server_default='0', nullable=True, comment='浏览量'),
    sa.Column('like_num', sa.Integer(), server_default='0', nullable=True, comment='点赞量'),
    sa.Column('collect_num', sa.Integer(), server_default='0', nullable=True, comment='收藏量'),
    sa.Column('comment_num', sa.Integer(), server_default='0', nullable=True, comment='评论量'),
    sa.Column('comment_status', sa.String(length=10), server_default='enabled', nullable=False, comment='评论状态: enabled/disabled'),
    sa.Column('status', sa.String(length=10), server_default='enabled', nullable=False, comment='状态: enabled/disabled'),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='文章表',
    mariadb_engine='InnoDB',
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_cms_post_category_id'), 'cms_post', ['category_id'], unique=False)
    op.create_index(op.f('ix_cms_post_pid'), 'cms_post', ['pid'], unique=False)
    op.create_index(op.f('ix_cms_post_title'), 'cms_post', ['title'], unique=False)
    op.create_index(op.f('ix_cms_post_user_id'), 'cms_post', ['user_id'], unique=False)
    op.create_table('cms_post_category',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='ID'),
    sa.Column('name', sa.String(length=50), nullable=False, comment='名称'),
    sa.Column('alias', sa.String(length=50), nullable=False, comment='URL别名'),
    sa.Column('keywords', sa.String(length=50), nullable=True, comment='关键字'),
    sa.Column('asc_sort_order', sa.Integer(), server_default='0', nullable=True, comment='排序'),
    sa.Column('status', sa.String(length=10), server_default='enabled', nullable=False, comment='状态: enabled/disabled'),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='文章分类',
    mariadb_engine='InnoDB',
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_cms_post_category_alias'), 'cms_post_category', ['alias'], unique=True)
    op.create_index(op.f('ix_cms_post_category_name'), 'cms_post_category', ['name'], unique=False)
    op.create_table('payment_channel',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='ID'),
    sa.Column('key', sa.String(length=50), nullable=True, comment='键名'),
    sa.Column('name', sa.String(length=50), nullable=True, comment='名称'),
    sa.Column('icon', sa.String(length=255), nullable=True, comment='图标'),
    sa.Column('locked', sa.String(length=10), server_default='no', nullable=True, comment='锁定: yes/no'),
    sa.Column('asc_sort_order', sa.Integer(), server_default='0', nullable=True, comment='排序'),
    sa.Column('status', sa.String(length=10), server_default='enabled', nullable=False, comment='状态: enabled/disabled'),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='支付渠道',
    mariadb_engine='InnoDB',
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_payment_channel_asc_sort_order'), 'payment_channel', ['asc_sort_order'], unique=False)
    op.create_index(op.f('ix_payment_channel_key'), 'payment_channel', ['key'], unique=True)
    op.create_table('payment_config',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='ID'),
    sa.Column('channel_id', sa.Integer(), nullable=False, comment='支付渠道ID'),
    sa.Column('channel_key', sa.String(length=50), nullable=False, comment='支付渠道KEY'),
    sa.Column('name', sa.String(length=50), nullable=True, comment='名称'),
    sa.Column('appname', sa.String(length=50), nullable=True, comment='支付平台APP名称'),
    sa.Column('appid', sa.String(length=50), nullable=False, comment='支付平台APPID'),
    sa.Column('mchid', sa.String(length=50), nullable=True, comment='支付平台商户ID'),
    sa.Column('miniappid', sa.String(length=50), nullable=True, comment='小程序APPID'),
    sa.Column('app_public_cert', sa.Text(), nullable=True, comment='应用公钥'),
    sa.Column('app_private_key', sa.Text(), nullable=True, comment='应用私钥'),
    sa.Column('app_secret_key', sa.Text(), nullable=True, comment='应用密钥'),
    sa.Column('platform_public_cert', sa.Text(), nullable=True, comment='平台公钥'),
    sa.Column('locked', sa.String(length=10), server_default='no', nullable=True, comment='锁定: yes/no'),
    sa.Column('asc_sort_order', sa.Integer(), server_default='0', nullable=True, comment='排序'),
    sa.Column('status', sa.String(length=10), server_default='enabled', nullable=False, comment='状态: enabled/disabled'),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='支付配置',
    mariadb_engine='InnoDB',
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_payment_config_asc_sort_order'), 'payment_config', ['asc_sort_order'], unique=False)
    op.create_index(op.f('ix_payment_config_channel_id'), 'payment_config', ['channel_id'], unique=False)
    op.create_table('system_option',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='ID'),
    sa.Column('option_name', sa.String(length=50), nullable=True, comment='选项名称'),
    sa.Column('option_value', sa.Text(), nullable=True, comment='选项值'),
    sa.Column('richtext', sa.SmallInteger(), server_default='0', nullable=True, comment='是否富文本'),
    sa.Column('position', sa.SmallInteger(), server_default='0', nullable=True, comment='位置'),
    sa.Column('autoload', sa.SmallInteger(), server_default='0', nullable=True, comment='自动加载'),
    sa.Column('lock', sa.SmallInteger(), server_default='0', nullable=True, comment='禁止删除'),
    sa.Column('public', sa.SmallInteger(), server_default='0', nullable=True, comment='是否公开'),
    sa.Column('memo', sa.String(length=255), nullable=True, comment='备注'),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='系统选项',
    mariadb_engine='InnoDB',
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_system_option_memo'), 'system_option', ['memo'], unique=False)
    op.create_index(op.f('ix_system_option_option_name'), 'system_option', ['option_name'], unique=False)
    op.create_index('position', 'system_option', ['autoload'], unique=False)
    op.create_table('user_account',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='ID'),
    sa.Column('pid', sa.Integer(), server_default='0', nullable=True, comment='所属上级'),
    sa.Column('agent_id', sa.Integer(), server_default='0', nullable=True, comment='所属代理'),
    sa.Column('phone_code', sa.String(length=10), server_default='86', nullable=True, comment='手机代码'),
    sa.Column('phone', sa.String(length=50), nullable=True, comment='手机'),
    sa.Column('email', sa.String(length=50), nullable=True, comment='邮箱'),
    sa.Column('nickname', sa.String(length=50), nullable=True, comment='昵称'),
    sa.Column('gender', sa.String(length=50), nullable=True, comment='性别'),
    sa.Column('avatar', sa.String(length=255), nullable=True, comment='头像'),
    sa.Column('promotion_code', sa.String(length=50), nullable=True, comment='推广码'),
    sa.Column('password_salt', sa.String(length=255), nullable=True, comment='密码盐'),
    sa.Column('password_hash', sa.String(length=255), nullable=True, comment='密码哈希'),
    sa.Column('role_id', sa.Integer(), server_default='0', nullable=True, comment='角色ID'),
    sa.Column('is_admin', sa.SmallInteger(), server_default='0', nullable=True, comment='是否管理员'),
    sa.Column('is_robot', sa.SmallInteger(), server_default='0', nullable=True, comment='是否机器人'),
    sa.Column('status', sa.String(length=10), server_default='enabled', nullable=False, comment='状态: enabled/disabled'),
    sa.Column('auto_memo', sa.String(length=255), nullable=True, comment='自动备注'),
    sa.Column('back_memo', sa.String(length=255), nullable=True, comment='后台备注'),
    sa.Column('wechat_openid', sa.String(length=50), nullable=True, comment='OpenID'),
    sa.Column('wechat_unionid', sa.String(length=50), nullable=True, comment='UnionID'),
    sa.Column('wechat_refresh_token', sa.String(length=255), nullable=True, comment='微信RefreshToken'),
    sa.Column('wechat_access_token', sa.String(length=255), nullable=True, comment='微信AccessToken'),
    sa.Column('wechat_access_token_expired_at', sa.Integer(), nullable=True, comment='微信AccessToken过期时间'),
    sa.Column('join_from', sa.SmallInteger(), server_default='0', nullable=True, comment='注册来源'),
    sa.Column('join_ip', sa.String(length=50), nullable=True, comment='注册IP'),
    sa.Column('join_at', sa.TIMESTAMP(), nullable=True, comment='注册时间'),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='用户表',
    mariadb_engine='InnoDB',
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_user_account_email'), 'user_account', ['email'], unique=True)
    op.create_index(op.f('ix_user_account_phone'), 'user_account', ['phone'], unique=True)
    op.create_index(op.f('ix_user_account_phone_code'), 'user_account', ['phone_code'], unique=False)
    op.create_index(op.f('ix_user_account_pid'), 'user_account', ['pid'], unique=False)
    op.create_index(op.f('ix_user_account_role_id'), 'user_account', ['role_id'], unique=False)
    op.create_index(op.f('ix_user_account_wechat_openid'), 'user_account', ['wechat_openid'], unique=False)
    op.create_index(op.f('ix_user_account_wechat_unionid'), 'user_account', ['wechat_unionid'], unique=False)
    op.create_table('user_balance',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='ID'),
    sa.Column('type', sa.SmallInteger(), nullable=False, comment='动账类型'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='用户ID'),
    sa.Column('related_id', sa.Integer(), server_default='0', nullable=True, comment='关联ID'),
    sa.Column('amount', sa.DECIMAL(precision=10, scale=4), nullable=False, comment='动账金额'),
    sa.Column('balance', sa.DECIMAL(precision=10, scale=4), nullable=False, comment='当前余额'),
    sa.Column('ip', sa.String(length=50), nullable=True, comment='IP'),
    sa.Column('hash', sa.String(length=32), nullable=True, comment='校验码'),
    sa.Column('auto_memo', sa.String(length=255), nullable=True, comment='自动备注'),
    sa.Column('back_memo', sa.String(length=255), nullable=True, comment='后台备注'),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='余额日志',
    mariadb_engine='InnoDB',
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_user_balance_related_id'), 'user_balance', ['related_id'], unique=False)
    op.create_index(op.f('ix_user_balance_user_id'), 'user_balance', ['user_id', 'type'], unique=False)
    op.create_table('user_balance_gift',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='ID'),
    sa.Column('type', sa.SmallInteger(), nullable=False, comment='动账类型'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='用户ID'),
    sa.Column('related_id', sa.Integer(), server_default='0', nullable=True, comment='关联ID'),
    sa.Column('amount', sa.DECIMAL(precision=10, scale=4), nullable=False, comment='动账金额'),
    sa.Column('balance', sa.DECIMAL(precision=10, scale=4), nullable=False, comment='当前余额'),
    sa.Column('ip', sa.String(length=50), nullable=True, comment='IP'),
    sa.Column('hash', sa.String(length=32), nullable=True, comment='校验码'),
    sa.Column('auto_memo', sa.String(length=255), nullable=True, comment='自动备注'),
    sa.Column('back_memo', sa.String(length=255), nullable=True, comment='后台备注'),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='赠送余额日志',
    mariadb_engine='InnoDB',
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_user_balance_gift_related_id'), 'user_balance_gift', ['related_id'], unique=False)
    op.create_index(op.f('ix_user_balance_gift_user_id'), 'user_balance_gift', ['user_id', 'type'], unique=False)
    op.create_table('user_balance_recharge',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='ID'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='用户ID'),
    sa.Column('trade_no', sa.String(length=32), nullable=False, comment='交易号'),
    sa.Column('amount', sa.DECIMAL(precision=10, scale=4), nullable=False, comment='充值数量'),
    sa.Column('price', sa.DECIMAL(precision=10, scale=4), nullable=False, comment='支付金额'),
    sa.Column('gift_amount', sa.DECIMAL(precision=10, scale=4), server_default='0', nullable=True, comment='赠送数量'),
    sa.Column('refund_amount', sa.DECIMAL(precision=10, scale=4), server_default='0', nullable=True, comment='退款数量'),
    sa.Column('refund_gift_amount', sa.DECIMAL(precision=10, scale=4), server_default='0', nullable=True, comment='退款赠送数量'),
    sa.Column('payment_status', sa.SmallInteger(), server_default='0', nullable=True, comment='状态'),
    sa.Column('payment_channel', sa.String(length=50), nullable=True, comment='支付渠道'),
    sa.Column('payment_appid', sa.String(length=50), nullable=True, comment='支付APPID'),
    sa.Column('payment_time', sa.TIMESTAMP(), nullable=True, comment='支付时间'),
    sa.Column('payment_response', sa.Text(), nullable=True, comment='支付结果'),
    sa.Column('refund_response', sa.Text(), nullable=True, comment='退款结果'),
    sa.Column('audit_user_id', sa.Integer(), server_default='0', nullable=True, comment='审核人员ID'),
    sa.Column('audit_user_name', sa.String(length=100), nullable=True, comment='审核人员姓名'),
    sa.Column('audit_reply', sa.String(length=255), nullable=True, comment='审核回复'),
    sa.Column('audit_time', sa.TIMESTAMP(), nullable=True, comment='审核时间'),
    sa.Column('audit_ip', sa.String(length=50), nullable=True, comment='审核人员IP地址'),
    sa.Column('user_ip', sa.String(length=50), nullable=True, comment='用户充值时的IP地址'),
    sa.Column('auto_memo', sa.String(length=255), nullable=True, comment='自动备注'),
    sa.Column('back_memo', sa.String(length=255), nullable=True, comment='后台备注'),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='余额充值日志',
    mariadb_engine='InnoDB',
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_user_balance_recharge_audit_user_id'), 'user_balance_recharge', ['audit_user_id'], unique=False)
    op.create_index(op.f('ix_user_balance_recharge_payment_channel'), 'user_balance_recharge', ['payment_channel'], unique=False)
    op.create_index(op.f('ix_user_balance_recharge_payment_status'), 'user_balance_recharge', ['payment_status'], unique=False)
    op.create_index(op.f('ix_user_balance_recharge_trade_no'), 'user_balance_recharge', ['trade_no'], unique=True)
    op.create_index(op.f('ix_user_balance_recharge_user_id'), 'user_balance_recharge', ['user_id'], unique=False)
    op.create_table('user_checkin',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='ID'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='用户ID'),
    sa.Column('type', sa.SmallInteger(), server_default='1', nullable=True, comment='类型 1:签到 2:补签'),
    sa.Column('total_days', sa.Integer(), server_default='0', nullable=True, comment='累计签到天数'),
    sa.Column('keep_days', sa.Integer(), server_default='1', nullable=True, comment='连续签到天数'),
    sa.Column('points', sa.Integer(), server_default='0', nullable=True, comment='获得积分'),
    sa.Column('related_type', sa.String(length=50), nullable=True, comment='关联类型'),
    sa.Column('related_id', sa.Integer(), server_default='0', nullable=True, comment='关联ID'),
    sa.Column('ip', sa.String(length=50), nullable=True, comment='IP地址'),
    sa.Column('user_agent', sa.String(length=500), nullable=True, comment='浏览器信息'),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True, comment='创建时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='签到日志',
    mariadb_engine='InnoDB',
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_user_checkin_related_type'), 'user_checkin', ['related_type'], unique=False)
    op.create_index(op.f('ix_user_checkin_user_id'), 'user_checkin', ['user_id', 'type'], unique=False)
    op.create_table('user_loginlog',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='ID'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='用户ID'),
    sa.Column('nickname', sa.String(length=50), nullable=True, comment='昵称'),
    sa.Column('ip', sa.String(length=50), nullable=True, comment='IP地址'),
    sa.Column('user_agent', sa.String(length=500), nullable=True, comment='浏览器信息'),
    sa.Column('memo', sa.String(length=255), nullable=True, comment='备注'),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True, comment='创建时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='登录日志',
    mariadb_engine='InnoDB',
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_user_loginlog_user_id'), 'user_loginlog', ['user_id'], unique=False)
    op.create_table('user_metadata',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='ID'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='用户ID'),
    sa.Column('meta_key', sa.String(length=50), nullable=False, comment='键'),
    sa.Column('meta_val', sa.Text(), nullable=True, comment='值'),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='用户元数据',
    mariadb_engine='InnoDB',
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_user_metadata_user_id'), 'user_metadata', ['user_id', 'meta_key'], unique=False)
    op.create_table('user_payment_account',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='ID'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='用户ID'),
    sa.Column('type', sa.String(length=50), server_default='alipay', nullable=True, comment='类型'),
    sa.Column('account', sa.String(length=50), nullable=False, comment='账号'),
    sa.Column('bank_name', sa.String(length=50), nullable=True, comment='银行名称'),
    sa.Column('bank_outlets', sa.String(length=255), nullable=True, comment='开户行'),
    sa.Column('bank_userphone', sa.String(length=50), nullable=True, comment='银行预留手机号'),
    sa.Column('total_withdraw', sa.DECIMAL(precision=10, scale=4), nullable=True, comment='累计提现'),
    sa.Column('status', sa.String(length=10), server_default='enabled', nullable=False, comment='状态: enabled/disabled'),
    sa.Column('auto_memo', sa.String(length=255), nullable=True, comment='自动备注'),
    sa.Column('user_memo', sa.String(length=255), nullable=True, comment='用户备注'),
    sa.Column('back_memo', sa.String(length=255), nullable=True, comment='后台备注'),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='用户支付账号',
    mariadb_engine='InnoDB',
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_user_payment_account_account'), 'user_payment_account', ['account'], unique=False)
    op.create_index(op.f('ix_user_payment_account_user_id'), 'user_payment_account', ['user_id', 'type', 'status'], unique=False)
    op.create_table('user_permission',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='ID'),
    sa.Column('pid', sa.Integer(), server_default='0', nullable=True, comment='上级ID'),
    sa.Column('name', sa.String(length=50), nullable=False, comment='名称'),
    sa.Column('icon', sa.String(length=50), nullable=True, comment='图标'),
    sa.Column('component_name', sa.String(length=50), nullable=True, comment='路由组件名称'),
    sa.Column('asc_sort_order', sa.Integer(), server_default='0', nullable=True, comment='排序'),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='权限表',
    mariadb_engine='InnoDB',
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_user_permission_pid'), 'user_permission', ['pid'], unique=False)
    op.create_table('user_point',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='ID'),
    sa.Column('type', sa.SmallInteger(), nullable=False, comment='动账类型'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='用户ID'),
    sa.Column('related_id', sa.Integer(), server_default='0', nullable=True, comment='关联ID'),
    sa.Column('amount', sa.Integer(), nullable=False, comment='动账点数'),
    sa.Column('balance', sa.Integer(), nullable=False, comment='当前余额'),
    sa.Column('ip', sa.String(length=50), nullable=True, comment='IP'),
    sa.Column('hash', sa.String(length=32), nullable=True, comment='校验码'),
    sa.Column('auto_memo', sa.String(length=255), nullable=True, comment='自动备注'),
    sa.Column('back_memo', sa.String(length=255), nullable=True, comment='后台备注'),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='积分日志',
    mariadb_engine='InnoDB',
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_user_point_related_id'), 'user_point', ['related_id'], unique=False)
    op.create_index(op.f('ix_user_point_user_id'), 'user_point', ['user_id', 'type'], unique=False)
    op.create_table('user_point_recharge',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='ID'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='用户ID'),
    sa.Column('trade_no', sa.String(length=32), nullable=False, comment='交易号'),
    sa.Column('amount', sa.DECIMAL(precision=10, scale=4), nullable=False, comment='充值金额'),
    sa.Column('points', sa.Integer(), nullable=False, comment='充值数量'),
    sa.Column('gift_points', sa.Integer(), server_default='0', nullable=True, comment='赠送数量'),
    sa.Column('refund_amount', sa.DECIMAL(precision=10, scale=4), server_default='0', nullable=True, comment='退款金额'),
    sa.Column('refund_points', sa.Integer(), server_default='0', nullable=True, comment='退款数量'),
    sa.Column('refund_gift_points', sa.Integer(), server_default='0', nullable=True, comment='退款赠送数量'),
    sa.Column('payment_status', sa.SmallInteger(), server_default='0', nullable=True, comment='状态'),
    sa.Column('payment_channel', sa.String(length=50), nullable=True, comment='支付渠道'),
    sa.Column('payment_appid', sa.String(length=50), nullable=True, comment='支付APPID'),
    sa.Column('payment_time', sa.TIMESTAMP(), nullable=True, comment='支付时间'),
    sa.Column('payment_response', sa.Text(), nullable=True, comment='支付结果'),
    sa.Column('refund_response', sa.Text(), nullable=True, comment='退款结果'),
    sa.Column('audit_user_id', sa.Integer(), server_default='0', nullable=True, comment='审核人员ID'),
    sa.Column('audit_user_name', sa.String(length=50), nullable=True, comment='审核人员姓名'),
    sa.Column('audit_reply', sa.String(length=255), nullable=True, comment='审核回复'),
    sa.Column('audit_time', sa.TIMESTAMP(), nullable=True, comment='审核时间'),
    sa.Column('audit_ip', sa.String(length=50), nullable=True, comment='审核人员IP地址'),
    sa.Column('user_ip', sa.String(length=50), nullable=True, comment='用户充值时的IP地址'),
    sa.Column('auto_memo', sa.String(length=255), nullable=True, comment='自动备注'),
    sa.Column('back_memo', sa.String(length=255), nullable=True, comment='后台备注'),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='积分充值日志',
    mariadb_engine='InnoDB',
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_user_point_recharge_audit_user_id'), 'user_point_recharge', ['audit_user_id'], unique=False)
    op.create_index(op.f('ix_user_point_recharge_payment_channel'), 'user_point_recharge', ['payment_channel'], unique=False)
    op.create_index(op.f('ix_user_point_recharge_payment_status'), 'user_point_recharge', ['payment_status'], unique=False)
    op.create_index(op.f('ix_user_point_recharge_trade_no'), 'user_point_recharge', ['trade_no'], unique=True)
    op.create_index(op.f('ix_user_point_recharge_user_id'), 'user_point_recharge', ['user_id'], unique=False)
    op.create_table('user_role',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='ID'),
    sa.Column('name', sa.String(length=50), nullable=False, comment='角色名称'),
    sa.Column('permissions', sa.Text(), nullable=True, comment='权限列表'),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='角色表',
    mariadb_engine='InnoDB',
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_user_role_name'), 'user_role', ['name'], unique=True)
    op.create_table('user_withdraw',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='ID'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='用户ID'),
    sa.Column('account_id', sa.Integer(), nullable=False, comment='提现账号ID'),
    sa.Column('trade_no', sa.String(length=32), nullable=False, comment='交易号'),
    sa.Column('amount', sa.DECIMAL(precision=10, scale=4), nullable=False, comment='提现金额'),
    sa.Column('actual_amount', sa.DECIMAL(precision=10, scale=4), nullable=False, comment='实际到账'),
    sa.Column('handling_fee', sa.DECIMAL(precision=10, scale=4), nullable=False, comment='手续费'),
    sa.Column('balance', sa.DECIMAL(precision=10, scale=4), nullable=False, comment='申请时余额'),
    sa.Column('payment_status', sa.SmallInteger(), server_default='0', nullable=True, comment='状态'),
    sa.Column('payment_channel', sa.String(length=50), nullable=True, comment='支付渠道'),
    sa.Column('payment_appid', sa.String(length=50), nullable=True, comment='支付APPID'),
    sa.Column('payment_time', sa.TIMESTAMP(), nullable=True, comment='支付时间'),
    sa.Column('payment_response', sa.Text(), nullable=True, comment='支付结果'),
    sa.Column('audit_status', sa.SmallInteger(), server_default='0', nullable=True, comment='审核状态'),
    sa.Column('audit_user_id', sa.Integer(), server_default='0', nullable=True, comment='审核人员ID'),
    sa.Column('audit_user_name', sa.String(length=100), nullable=True, comment='审核人员姓名'),
    sa.Column('audit_reply', sa.String(length=255), nullable=True, comment='审核回复'),
    sa.Column('audit_time', sa.TIMESTAMP(), nullable=True, comment='审核时间'),
    sa.Column('audit_ip', sa.String(length=50), nullable=True, comment='审核人员IP地址'),
    sa.Column('user_ip', sa.String(length=50), nullable=True, comment='用户申请时的IP地址'),
    sa.Column('auto_memo', sa.String(length=255), nullable=True, comment='自动备注'),
    sa.Column('back_memo', sa.String(length=255), nullable=True, comment='后台备注'),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='提现日志',
    mariadb_engine='InnoDB',
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_user_withdraw_account_id'), 'user_withdraw', ['account_id'], unique=False)
    op.create_index(op.f('ix_user_withdraw_audit_status'), 'user_withdraw', ['audit_status'], unique=False)
    op.create_index(op.f('ix_user_withdraw_audit_user_id'), 'user_withdraw', ['audit_user_id'], unique=False)
    op.create_index(op.f('ix_user_withdraw_user_id'), 'user_withdraw', ['user_id', 'payment_status'], unique=False)
    op.create_table('wechat_media_platform',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='ID'),
    sa.Column('type', sa.String(length=50), nullable=False, comment='账号类型'),
    sa.Column('appid', sa.String(length=50), nullable=True, comment='AppID'),
    sa.Column('appname', sa.String(length=50), nullable=True, comment='AppName'),
    sa.Column('appsecret', sa.String(length=50), nullable=True, comment='AppSecret'),
    sa.Column('token', sa.String(length=50), nullable=True, comment='Token'),
    sa.Column('aeskey', sa.String(length=43), nullable=True, comment='AesKey'),
    sa.Column('status', sa.String(length=10), server_default='enabled', nullable=False, comment='状态: enabled/disabled'),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='微信媒体平台',
    mariadb_engine='InnoDB',
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_wechat_media_platform_appid'), 'wechat_media_platform', ['appid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wechat_media_platform_appid'), table_name='wechat_media_platform')
    op.drop_table('wechat_media_platform')
    op.drop_index(op.f('ix_user_withdraw_user_id'), table_name='user_withdraw')
    op.drop_index(op.f('ix_user_withdraw_audit_user_id'), table_name='user_withdraw')
    op.drop_index(op.f('ix_user_withdraw_audit_status'), table_name='user_withdraw')
    op.drop_index(op.f('ix_user_withdraw_account_id'), table_name='user_withdraw')
    op.drop_table('user_withdraw')
    op.drop_index(op.f('ix_user_role_name'), table_name='user_role')
    op.drop_table('user_role')
    op.drop_index(op.f('ix_user_point_recharge_user_id'), table_name='user_point_recharge')
    op.drop_index(op.f('ix_user_point_recharge_trade_no'), table_name='user_point_recharge')
    op.drop_index(op.f('ix_user_point_recharge_payment_status'), table_name='user_point_recharge')
    op.drop_index(op.f('ix_user_point_recharge_payment_channel'), table_name='user_point_recharge')
    op.drop_index(op.f('ix_user_point_recharge_audit_user_id'), table_name='user_point_recharge')
    op.drop_table('user_point_recharge')
    op.drop_index(op.f('ix_user_point_user_id'), table_name='user_point')
    op.drop_index(op.f('ix_user_point_related_id'), table_name='user_point')
    op.drop_table('user_point')
    op.drop_index(op.f('ix_user_permission_pid'), table_name='user_permission')
    op.drop_table('user_permission')
    op.drop_index(op.f('ix_user_payment_account_user_id'), table_name='user_payment_account')
    op.drop_index(op.f('ix_user_payment_account_account'), table_name='user_payment_account')
    op.drop_table('user_payment_account')
    op.drop_index(op.f('ix_user_metadata_user_id'), table_name='user_metadata')
    op.drop_table('user_metadata')
    op.drop_index(op.f('ix_user_loginlog_user_id'), table_name='user_loginlog')
    op.drop_table('user_loginlog')
    op.drop_index(op.f('ix_user_checkin_user_id'), table_name='user_checkin')
    op.drop_index(op.f('ix_user_checkin_related_type'), table_name='user_checkin')
    op.drop_table('user_checkin')
    op.drop_index(op.f('ix_user_balance_recharge_user_id'), table_name='user_balance_recharge')
    op.drop_index(op.f('ix_user_balance_recharge_trade_no'), table_name='user_balance_recharge')
    op.drop_index(op.f('ix_user_balance_recharge_payment_status'), table_name='user_balance_recharge')
    op.drop_index(op.f('ix_user_balance_recharge_payment_channel'), table_name='user_balance_recharge')
    op.drop_index(op.f('ix_user_balance_recharge_audit_user_id'), table_name='user_balance_recharge')
    op.drop_table('user_balance_recharge')
    op.drop_index(op.f('ix_user_balance_gift_user_id'), table_name='user_balance_gift')
    op.drop_index(op.f('ix_user_balance_gift_related_id'), table_name='user_balance_gift')
    op.drop_table('user_balance_gift')
    op.drop_index(op.f('ix_user_balance_user_id'), table_name='user_balance')
    op.drop_index(op.f('ix_user_balance_related_id'), table_name='user_balance')
    op.drop_table('user_balance')
    op.drop_index(op.f('ix_user_account_wechat_unionid'), table_name='user_account')
    op.drop_index(op.f('ix_user_account_wechat_openid'), table_name='user_account')
    op.drop_index(op.f('ix_user_account_role_id'), table_name='user_account')
    op.drop_index(op.f('ix_user_account_pid'), table_name='user_account')
    op.drop_index(op.f('ix_user_account_phone_code'), table_name='user_account')
    op.drop_index(op.f('ix_user_account_phone'), table_name='user_account')
    op.drop_index(op.f('ix_user_account_email'), table_name='user_account')
    op.drop_table('user_account')
    op.drop_index('position', table_name='system_option')
    op.drop_index(op.f('ix_system_option_option_name'), table_name='system_option')
    op.drop_index(op.f('ix_system_option_memo'), table_name='system_option')
    op.drop_table('system_option')
    op.drop_index(op.f('ix_payment_config_channel_id'), table_name='payment_config')
    op.drop_index(op.f('ix_payment_config_asc_sort_order'), table_name='payment_config')
    op.drop_table('payment_config')
    op.drop_index(op.f('ix_payment_channel_key'), table_name='payment_channel')
    op.drop_index(op.f('ix_payment_channel_asc_sort_order'), table_name='payment_channel')
    op.drop_table('payment_channel')
    op.drop_index(op.f('ix_cms_post_category_name'), table_name='cms_post_category')
    op.drop_index(op.f('ix_cms_post_category_alias'), table_name='cms_post_category')
    op.drop_table('cms_post_category')
    op.drop_index(op.f('ix_cms_post_user_id'), table_name='cms_post')
    op.drop_index(op.f('ix_cms_post_title'), table_name='cms_post')
    op.drop_index(op.f('ix_cms_post_pid'), table_name='cms_post')
    op.drop_index(op.f('ix_cms_post_category_id'), table_name='cms_post')
    op.drop_table('cms_post')
    op.drop_index(op.f('ix_cms_media_related_id'), table_name='cms_media')
    op.drop_index(op.f('ix_cms_media_op_user_id'), table_name='cms_media')
    op.drop_index(op.f('ix_cms_media_file_type'), table_name='cms_media')
    op.drop_table('cms_media')
    op.drop_index(op.f('ix_cms_city_pinyin'), table_name='cms_city')
    op.drop_index(op.f('ix_cms_city_pid'), table_name='cms_city')
    op.drop_index(op.f('ix_cms_city_name'), table_name='cms_city')
    op.drop_table('cms_city')
    op.drop_index(op.f('ix_cms_banner_adspace_id'), table_name='cms_banner')
    op.drop_table('cms_banner')
    op.drop_index(op.f('ix_cms_adspace_name'), table_name='cms_adspace')
    op.drop_table('cms_adspace')
    # ### end Alembic commands ###
