"""Init

Revision ID: eda43762eb7e
Revises: 
Create Date: 2024-05-28 11:27:54.441257

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'eda43762eb7e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cms_media',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='ID'),
    sa.Column('file_name', sa.String(length=255), nullable=True, comment='文件名称'),
    sa.Column('file_type', sa.String(length=32), nullable=True, comment='文件类型'),
    sa.Column('file_size', sa.Integer(), nullable=True, comment='文件大小'),
    sa.Column('file_path', sa.String(length=255), nullable=True, comment='文件路径'),
    sa.Column('oss_url', sa.String(length=255), nullable=True, comment='OSS地址'),
    sa.Column('op_user_id', sa.Integer(), nullable=False, comment='操作员ID'),
    sa.Column('op_user_name', sa.String(length=100), nullable=False, comment='操作员名称'),
    sa.Column('related_type', sa.String(length=32), nullable=True, comment='关联类别'),
    sa.Column('related_id', sa.Integer(), server_default='0', nullable=True, comment='关联ID'),
    sa.Column('view_num', sa.Integer(), server_default='0', nullable=True, comment='浏览量/下载量'),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True, comment='创建时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='媒体文件',
    mariadb_engine='InnoDB',
    mysql_engine='InnoDB'
    )
    op.create_index('idx_file_type', 'cms_media', ['file_type'], unique=False)
    op.create_index('idx_op_user_id', 'cms_media', ['op_user_id'], unique=False)
    op.create_index('idx_related', 'cms_media', ['related_type', 'related_id'], unique=False)
    op.create_table('cms_post',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='ID'),
    sa.Column('pid', sa.Integer(), server_default='0', nullable=True, comment='上级ID'),
    sa.Column('category_id', sa.Integer(), server_default='0', nullable=True, comment='分类ID'),
    sa.Column('user_id', sa.Integer(), server_default='0', nullable=True, comment='用户ID'),
    sa.Column('title', sa.String(length=255), nullable=False, comment='标题'),
    sa.Column('subtitle', sa.String(length=255), nullable=False, comment='副标题'),
    sa.Column('keywords', sa.String(length=50), nullable=True, comment='关键字'),
    sa.Column('digest', sa.String(length=50), nullable=True, comment='摘要'),
    sa.Column('content', mysql.MEDIUMTEXT(), nullable=False, comment='内容'),
    sa.Column('author', sa.String(length=50), nullable=True, comment='作者'),
    sa.Column('editor', sa.String(length=50), nullable=True, comment='责编'),
    sa.Column('source', sa.String(length=50), nullable=True, comment='来源'),
    sa.Column('source_url', sa.String(length=1000), nullable=True, comment='来源URL'),
    sa.Column('hero_image_url', sa.String(length=1000), nullable=True, comment='首图'),
    sa.Column('price', sa.DECIMAL(precision=10, scale=4), server_default='0', nullable=True, comment='价格'),
    sa.Column('price_point', sa.Integer(), server_default='0', nullable=True, comment='积分价格'),
    sa.Column('view_num', sa.Integer(), server_default='0', nullable=True, comment='浏览量'),
    sa.Column('like_num', sa.Integer(), server_default='0', nullable=True, comment='点赞量'),
    sa.Column('collect_num', sa.Integer(), server_default='0', nullable=True, comment='收藏量'),
    sa.Column('comment_num', sa.Integer(), server_default='0', nullable=True, comment='评论量'),
    sa.Column('comment_status', sa.SmallInteger(), server_default='1', nullable=True, comment='评论状态'),
    sa.Column('status', sa.SmallInteger(), server_default='1', nullable=True, comment='状态'),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='文章表',
    mariadb_engine='InnoDB',
    mysql_engine='InnoDB'
    )
    op.create_table('cms_post_category',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='ID'),
    sa.Column('name', sa.String(length=50), nullable=False, comment='名称'),
    sa.Column('alias', sa.String(length=50), nullable=False, comment='URL别名'),
    sa.Column('keywords', sa.String(length=50), nullable=True, comment='关键字'),
    sa.Column('asc_sort_order', sa.Integer(), server_default='0', nullable=True, comment='排序'),
    sa.Column('status', sa.SmallInteger(), server_default='1', nullable=True, comment='状态'),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='文章分类',
    mariadb_engine='InnoDB',
    mysql_engine='InnoDB'
    )
    op.create_index('idx_name', 'cms_post_category', ['name'], unique=False)
    op.create_table('system_option',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='ID'),
    sa.Column('option_name', sa.String(length=32), nullable=True, comment='选项名称'),
    sa.Column('option_value', sa.Text(), nullable=True, comment='选项值'),
    sa.Column('richtext', sa.SmallInteger(), server_default='0', nullable=True, comment='是否富文本'),
    sa.Column('position', sa.SmallInteger(), server_default='0', nullable=True, comment='位置'),
    sa.Column('autoload', sa.SmallInteger(), server_default='0', nullable=True, comment='自动加载'),
    sa.Column('lock', sa.SmallInteger(), server_default='0', nullable=True, comment='禁止删除'),
    sa.Column('memo', sa.String(length=255), nullable=True, comment='备注'),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='系统选项',
    mariadb_engine='InnoDB',
    mysql_engine='InnoDB'
    )
    op.create_index('idx_memo', 'system_option', ['memo'], unique=False)
    op.create_index('idx_option_name', 'system_option', ['option_name'], unique=False)
    op.create_index('idx_position_autoload', 'system_option', ['position', 'autoload'], unique=False)
    op.create_table('user_account',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='ID'),
    sa.Column('pid', sa.Integer(), server_default='0', nullable=True, comment='所属上级'),
    sa.Column('agent_id', sa.Integer(), server_default='0', nullable=True, comment='所属代理'),
    sa.Column('phone_code', sa.String(length=10), server_default='86', nullable=True, comment='手机代码'),
    sa.Column('phone', sa.String(length=50), nullable=True, comment='手机'),
    sa.Column('email', sa.String(length=50), nullable=True, comment='邮箱'),
    sa.Column('nickname', sa.String(length=50), nullable=True, comment='昵称'),
    sa.Column('gender', sa.String(length=50), nullable=True, comment='性别'),
    sa.Column('avatar', sa.String(length=255), nullable=True, comment='头像'),
    sa.Column('promotion_code', sa.String(length=50), nullable=True, comment='推广码'),
    sa.Column('password_salt', sa.String(length=255), nullable=True, comment='密码盐'),
    sa.Column('password_hash', sa.String(length=255), nullable=True, comment='密码哈希'),
    sa.Column('role_id', sa.Integer(), server_default='0', nullable=True, comment='角色ID'),
    sa.Column('is_admin', sa.SmallInteger(), server_default='0', nullable=True, comment='是否管理员'),
    sa.Column('is_robot', sa.SmallInteger(), server_default='0', nullable=True, comment='是否机器人'),
    sa.Column('status', sa.SmallInteger(), server_default='1', nullable=True, comment='状态'),
    sa.Column('auto_memo', sa.String(length=255), nullable=True, comment='自动备注'),
    sa.Column('back_memo', sa.String(length=255), nullable=True, comment='后台备注'),
    sa.Column('wechat_openid', sa.String(length=50), nullable=True, comment='OpenID'),
    sa.Column('wechat_unionid', sa.String(length=50), nullable=True, comment='UnionID'),
    sa.Column('wechat_refresh_token', sa.String(length=255), nullable=True, comment='微信RefreshToken'),
    sa.Column('wechat_access_token', sa.String(length=255), nullable=True, comment='微信AccessToken'),
    sa.Column('wechat_access_token_expired_at', sa.Integer(), nullable=True, comment='微信AccessToken过期时间'),
    sa.Column('join_from', sa.SmallInteger(), server_default='0', nullable=True, comment='注册来源'),
    sa.Column('join_ip', sa.String(length=50), nullable=True, comment='注册IP'),
    sa.Column('join_at', sa.TIMESTAMP(), nullable=True, comment='注册时间'),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='用户表',
    mariadb_engine='InnoDB',
    mysql_engine='InnoDB'
    )
    op.create_index('idx_email', 'user_account', ['email'], unique=True)
    op.create_index('idx_phone', 'user_account', ['phone'], unique=True)
    op.create_index('idx_pid', 'user_account', ['pid'], unique=False)
    op.create_index('idx_role', 'user_account', ['role_id'], unique=False)
    op.create_index('idx_wechat_openid', 'user_account', ['wechat_openid'], unique=False)
    op.create_index('idx_wechat_unionid', 'user_account', ['wechat_unionid'], unique=False)
    op.create_table('user_balance',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='ID'),
    sa.Column('type', sa.SmallInteger(), nullable=False, comment='动账类型'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='用户ID'),
    sa.Column('related_id', sa.Integer(), server_default='0', nullable=True, comment='关联ID'),
    sa.Column('amount', sa.DECIMAL(precision=10, scale=4), nullable=False, comment='动账金额'),
    sa.Column('balance', sa.DECIMAL(precision=10, scale=4), nullable=False, comment='当前余额'),
    sa.Column('ip', sa.String(length=50), nullable=True, comment='IP'),
    sa.Column('hash', sa.String(length=32), nullable=True, comment='校验码'),
    sa.Column('auto_memo', sa.String(length=255), nullable=True, comment='自动备注'),
    sa.Column('back_memo', sa.String(length=255), nullable=True, comment='后台备注'),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='余额日志',
    mariadb_engine='InnoDB',
    mysql_engine='InnoDB'
    )
    op.create_index('idx_type_related_id', 'user_balance', ['type', 'related_id'], unique=False)
    op.create_index('idx_user_id_created_at', 'user_balance', ['user_id', 'created_at'], unique=False)
    op.create_index('idx_user_id_type', 'user_balance', ['user_id', 'type'], unique=False)
    op.create_table('user_checkin',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='ID'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='用户ID'),
    sa.Column('type', sa.SmallInteger(), server_default='1', nullable=True, comment='类型'),
    sa.Column('total_days', sa.Integer(), server_default='0', nullable=True, comment='累计签到天数'),
    sa.Column('keep_days', sa.Integer(), server_default='1', nullable=True, comment='连续签到天数'),
    sa.Column('points', sa.Integer(), server_default='0', nullable=True, comment='获得积分'),
    sa.Column('related_type', sa.String(length=100), nullable=True, comment='关联类型'),
    sa.Column('related_id', sa.Integer(), server_default='0', nullable=True, comment='关联ID'),
    sa.Column('ip', sa.String(length=50), nullable=True, comment='IP地址'),
    sa.Column('user_agent', sa.String(length=500), nullable=True, comment='浏览器信息'),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True, comment='创建时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='签到日志',
    mariadb_engine='InnoDB',
    mysql_engine='InnoDB'
    )
    op.create_index('idx_related', 'user_checkin', ['related_type', 'related_id'], unique=False)
    op.create_index('idx_user_id_type', 'user_checkin', ['user_id', 'type'], unique=False)
    op.create_table('user_loginlog',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='ID'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='用户ID'),
    sa.Column('nickname', sa.String(length=50), nullable=True, comment='昵称'),
    sa.Column('ip', sa.String(length=50), nullable=True, comment='IP地址'),
    sa.Column('user_agent', sa.String(length=500), nullable=True, comment='浏览器信息'),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True, comment='创建时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='登录日志',
    mariadb_engine='InnoDB',
    mysql_engine='InnoDB'
    )
    op.create_table('user_metadata',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='ID'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='用户ID'),
    sa.Column('meta_key', sa.String(length=50), nullable=False, comment='键'),
    sa.Column('meta_val', sa.Text(), nullable=True, comment='值'),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='用户元数据',
    mariadb_engine='InnoDB',
    mysql_engine='InnoDB'
    )
    op.create_index('idx_search', 'user_metadata', ['user_id', 'meta_key'], unique=False)
    op.create_table('user_payment_account',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='ID'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='用户ID'),
    sa.Column('type', sa.SmallInteger(), server_default='1', nullable=True, comment='类型'),
    sa.Column('account', sa.String(length=255), nullable=False, comment='账号'),
    sa.Column('bank_name', sa.String(length=255), nullable=True, comment='银行名称'),
    sa.Column('bank_outlets', sa.String(length=255), nullable=True, comment='开户行'),
    sa.Column('bank_userphone', sa.String(length=255), nullable=True, comment='银行预留手机号'),
    sa.Column('total_withdraw', sa.DECIMAL(precision=10, scale=2), nullable=True, comment='累计提现'),
    sa.Column('status', sa.SmallInteger(), server_default='1', nullable=True, comment='状态'),
    sa.Column('auto_memo', sa.String(length=255), nullable=True, comment='自动备注'),
    sa.Column('user_memo', sa.String(length=255), nullable=True, comment='用户备注'),
    sa.Column('back_memo', sa.String(length=255), nullable=True, comment='后台备注'),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True, comment='创建时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='用户支付账号',
    mariadb_engine='InnoDB',
    mysql_engine='InnoDB'
    )
    op.create_index('idx_type_account', 'user_payment_account', ['type', 'account'], unique=False)
    op.create_index('idx_user_id_type_status', 'user_payment_account', ['user_id', 'type', 'status'], unique=False)
    op.create_table('user_permission',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='ID'),
    sa.Column('pid', sa.Integer(), server_default='0', nullable=True, comment='上级ID'),
    sa.Column('name', sa.String(length=50), nullable=False, comment='名称'),
    sa.Column('icon', sa.String(length=50), nullable=True, comment='图标'),
    sa.Column('component_name', sa.String(length=50), nullable=True, comment='路由组件名称'),
    sa.Column('asc_sort_order', sa.Integer(), server_default='0', nullable=True, comment='排序'),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='权限表',
    mariadb_engine='InnoDB',
    mysql_engine='InnoDB'
    )
    op.create_table('user_point',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='ID'),
    sa.Column('type', sa.SmallInteger(), nullable=False, comment='动账类型'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='用户ID'),
    sa.Column('related_id', sa.Integer(), server_default='0', nullable=True, comment='关联ID'),
    sa.Column('amount', sa.Integer(), nullable=False, comment='动账点数'),
    sa.Column('balance', sa.Integer(), nullable=False, comment='当前余额'),
    sa.Column('ip', sa.String(length=50), nullable=True, comment='IP'),
    sa.Column('hash', sa.String(length=32), nullable=True, comment='校验码'),
    sa.Column('auto_memo', sa.String(length=255), nullable=True, comment='自动备注'),
    sa.Column('back_memo', sa.String(length=255), nullable=True, comment='后台备注'),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='积分日志',
    mariadb_engine='InnoDB',
    mysql_engine='InnoDB'
    )
    op.create_index('idx_type_related_id', 'user_point', ['type', 'related_id'], unique=False)
    op.create_index('idx_user_id_created_at', 'user_point', ['user_id', 'created_at'], unique=False)
    op.create_index('idx_user_id_type', 'user_point', ['user_id', 'type'], unique=False)
    op.create_table('user_role',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='ID'),
    sa.Column('name', sa.String(length=50), nullable=False, comment='角色名称'),
    sa.Column('permissions', sa.Text(), nullable=True, comment='权限列表'),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='角色表',
    mariadb_engine='InnoDB',
    mysql_engine='InnoDB'
    )
    op.create_table('user_withdraw',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='ID'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='用户ID'),
    sa.Column('account_id', sa.Integer(), nullable=False, comment='提现账号ID'),
    sa.Column('trade_no', sa.String(length=32), nullable=False, comment='交易号'),
    sa.Column('amount', sa.DECIMAL(precision=10, scale=2), nullable=False, comment='提现金额'),
    sa.Column('actual_amount', sa.DECIMAL(precision=10, scale=2), nullable=False, comment='实际到账'),
    sa.Column('handling_fee', sa.DECIMAL(precision=10, scale=2), nullable=False, comment='手续费'),
    sa.Column('balance', sa.DECIMAL(precision=10, scale=2), nullable=False, comment='申请时余额'),
    sa.Column('payment_status', sa.SmallInteger(), server_default='0', nullable=True, comment='状态'),
    sa.Column('payment_tool', sa.String(length=50), nullable=True, comment='支付方式'),
    sa.Column('payment_time', sa.TIMESTAMP(), nullable=True, comment='支付时间'),
    sa.Column('payment_response', sa.Text(), nullable=True, comment='支付结果'),
    sa.Column('audit_status', sa.SmallInteger(), server_default='0', nullable=True, comment='审核状态'),
    sa.Column('audit_user_id', sa.Integer(), server_default='0', nullable=True, comment='审核人员ID'),
    sa.Column('audit_user_name', sa.String(length=100), nullable=True, comment='审核人员姓名'),
    sa.Column('audit_reply', sa.String(length=255), nullable=True, comment='审核回复'),
    sa.Column('audit_time', sa.TIMESTAMP(), nullable=True, comment='审核时间'),
    sa.Column('audit_ip', sa.String(length=50), nullable=True, comment='审核人员IP地址'),
    sa.Column('user_ip', sa.String(length=50), nullable=True, comment='用户申请时的IP地址'),
    sa.Column('auto_memo', sa.String(length=255), nullable=True, comment='自动备注'),
    sa.Column('back_memo', sa.String(length=255), nullable=True, comment='后台备注'),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='提现日志',
    mariadb_engine='InnoDB',
    mysql_engine='InnoDB'
    )
    op.create_index('idx_account_id', 'user_withdraw', ['account_id'], unique=False)
    op.create_index('idx_audit_status', 'user_withdraw', ['audit_status'], unique=False)
    op.create_index('idx_audit_user_id', 'user_withdraw', ['audit_user_id'], unique=False)
    op.create_index('idx_created_at', 'user_withdraw', ['created_at'], unique=False)
    op.create_index('idx_user_id_payment_status', 'user_withdraw', ['user_id', 'payment_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_user_id_payment_status', table_name='user_withdraw')
    op.drop_index('idx_created_at', table_name='user_withdraw')
    op.drop_index('idx_audit_user_id', table_name='user_withdraw')
    op.drop_index('idx_audit_status', table_name='user_withdraw')
    op.drop_index('idx_account_id', table_name='user_withdraw')
    op.drop_table('user_withdraw')
    op.drop_table('user_role')
    op.drop_index('idx_user_id_type', table_name='user_point')
    op.drop_index('idx_user_id_created_at', table_name='user_point')
    op.drop_index('idx_type_related_id', table_name='user_point')
    op.drop_table('user_point')
    op.drop_table('user_permission')
    op.drop_index('idx_user_id_type_status', table_name='user_payment_account')
    op.drop_index('idx_type_account', table_name='user_payment_account')
    op.drop_table('user_payment_account')
    op.drop_index('idx_search', table_name='user_metadata')
    op.drop_table('user_metadata')
    op.drop_table('user_loginlog')
    op.drop_index('idx_user_id_type', table_name='user_checkin')
    op.drop_index('idx_related', table_name='user_checkin')
    op.drop_table('user_checkin')
    op.drop_index('idx_user_id_type', table_name='user_balance')
    op.drop_index('idx_user_id_created_at', table_name='user_balance')
    op.drop_index('idx_type_related_id', table_name='user_balance')
    op.drop_table('user_balance')
    op.drop_index('idx_wechat_unionid', table_name='user_account')
    op.drop_index('idx_wechat_openid', table_name='user_account')
    op.drop_index('idx_role', table_name='user_account')
    op.drop_index('idx_pid', table_name='user_account')
    op.drop_index('idx_phone', table_name='user_account')
    op.drop_index('idx_email', table_name='user_account')
    op.drop_table('user_account')
    op.drop_index('idx_position_autoload', table_name='system_option')
    op.drop_index('idx_option_name', table_name='system_option')
    op.drop_index('idx_memo', table_name='system_option')
    op.drop_table('system_option')
    op.drop_index('idx_name', table_name='cms_post_category')
    op.drop_table('cms_post_category')
    op.drop_table('cms_post')
    op.drop_index('idx_related', table_name='cms_media')
    op.drop_index('idx_op_user_id', table_name='cms_media')
    op.drop_index('idx_file_type', table_name='cms_media')
    op.drop_table('cms_media')
    # ### end Alembic commands ###
